### ISSUE TITLE
Create a `makeRelative` function?

### ISSUE THREAD

**Issue by chrisdotcode** [fpco/haskell-filesystem#1]
That would convert `/home/chrisdotcode/code` into `home/chrisdotcode/code`.

Unless I'm missing something, this seems as simple as:

``` haskell
makeRelative :: FilePath -> FilePath
makeRelative f = f { pathRoot = Nothing }
```

To the best of my knowledge, this is impossible to implement outside of the package, because the data constructor is opaque.

**Comment by snoyberg** [comment]
Note that I've just announced that these libraries will be deprecated in favor of filepath and directory: https://plus.google.com/+MichaelSnoyman/posts/Ft5hnPqpgEx
