### ISSUE TITLE
PLATFORM_PATH_FORMAT promotes platform dependent code

### ISSUE THREAD

**Issue by brendanhay** [fpco/haskell-filesystem#12]
The [conditionally set](https://github.com/fpco/haskell-filesystem/blob/797f48ef9b44dc1b0b1a94f73ab110e58e2c42e5/system-filepath/lib/Filesystem/Path/CurrentOS.hs#L47) `PLATFORM_PATH_FORMAT` is exposed in a fairly poor way to the user making it easy to run into builds that are ironically platform dependent.

If you unknowingly use a function that returns `PLATFORM_PATH_FORMAT`  such as `encode :: FilePath -> PLATFORM_PATH_FORMAT`, rather than `encodeString` or `fromText`, when you compile the same code on a different platform you invariably end up with a broken build, due to an error like: Couldn't match expected type `ByteString` with `Text` (or vice versa).

Perhaps hiding the `PLATFORM_PATH_FORMAT` from the user entirely, or make use of some other abstraction which is independent of the compilation platform.

**Comment by brendanhay** [comment]
Documenting this pitfall might also be a nice quick fix!

**Comment by snoyberg** [comment]
I'd be happy for a PR on the doc fix. We have some plans around fixes to a number of issues in this library, which we'll be announcing in the near future.
