### ISSUE TITLE
Quickcheck failing  tests.validity.windows

### ISSUE THREAD

**Issue by teh** [fpco/haskell-filesystem#7]
As so often with filesytems I'm not sure whether this is my weird setup or an actual bug. Anyway, FS is ext4 on `Linux zap 3.14-1-amd64 #1 SMP Debian 3.14.9-1 (2014-06-30) x86_64 GNU/Linux`

```
$ export | grep LANG
declare -x LANG="en_GB.UTF-8"
declare -x LANGUAGE="en_GB:en"
```

```
[ FAIL  ] tests.validity.windows
  note: seed=8537359037766974241

    *** Failed! Falsifiable (after 43 tests): 
FilePath "$5\EOT\t\147jC*\199/\FSk5\DELVr[|/?^/\212g\194/\173\243d=/?^K+BY/\SOHg\bl/\b/B/\ACK\144\EMr\228\190<n\181/PF\198dB:?A/\149\NAK\244\bl]\SYN/i\239/\161/\225\FSu`\231\fH\248)l/<LZ~/\166\226\224\206;\251b\212m\224/\135N/-\159/I\176C@B/Qs\156\226\r\212/k\173\148\229/&Qd\130b\f&5/\SYN\188|@\153y/9q\241\242\136O; \FS/+5=(\CAN\te#&/L?/},oU/#\NAK\r\221\220f]v/$/\251\US\180)\FS\t\215q\EOT/s\ETB\148\STXw/\153\DC3/\244/*<p-\riz\GSY/M\DC3\DC4=\135
```

**Comment by snoyberg** [comment]
Thank you for the report. I'm aware that the test suite (and the implementation for that matter) need some significant overhaul, which we're starting to look towards (pinging @chrisdone, let's plan this out).

**Comment by snoyberg** [comment]
Note that I've just announced that these libraries will be deprecated in favor of filepath and directory: https://plus.google.com/+MichaelSnoyman/posts/Ft5hnPqpgEx

**Comment by teh** [comment]
Thanks! Closing this.
