### ISSUE TITLE
On Windows, `withHANDLE` should use a zero parameter instead of `Win32.gENERIC_READ`

### ISSUE THREAD

**Issue by hgolden** [fpco/haskell-filesystem#8]
This issue is referred upstream from [https://github.com/Gabriel439/Haskell-Turtle-Library/issues/35].

Gabriel Gonzalez's Turtle program calls `Filesystem.getModified` to find the modification time of a file. This works OK under Windows unless the "file" is a directory. In this case, the Windows `createFile` will fail because Windows attempts to open the directory. As explained on MSDN, a zero parameter should be used instead of `Win32.gENERIC_READ` to access directory metadata (see [https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858%28v=vs.85%29.aspx]) in the following code:
```haskell
#ifdef CABAL_OS_WINDOWS

withHANDLE :: FilePath -> (Win32.HANDLE -> IO a) -> IO a
withHANDLE path = Exc.bracket open close where
    open = Win32.createFile
        (encodeString path)
        Win32.gENERIC_READ
        (Win32.fILE_SHARE_READ .|. Win32.fILE_SHARE_WRITE)
        Nothing
        Win32.oPEN_EXISTING
        0
        Nothing
    close = Win32.closeHandle
```
I don't know if the code with the zero parameter will work correctly on files. It may be necessary to try the code with a zero parameter first and then try again with `Win32.gENERIC_READ` if the file is *not* a directory.

**Comment by snoyberg** [comment]
What would help a lot here would be a simple reproducing test case.

**Comment by hgolden** [comment]
The test case is on the downstream bug report [Gabriel439/Haskell-Turtle-Library#35]:
```console
C:\Users\hgolden\Documents\Automation\Haskell>ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/ :? for help
[snip...]
Prelude> import Turtle
Prelude Turtle> dir <- pwd
[snip...]
Prelude Turtle> time <- datefile dir
*** Exception: CreateFile "C:\Users\hgolden\Documents\Automation\Haskell": permission denied (Access is denied.)
Prelude Turtle>
```
It appears that this problem only occurs if the file is a directory. For example, this works:
```console
Prelude Turtle> time <- datefile $ fromString ".\\example.hs"
Prelude Turtle> print time
2015-03-16 21:40:36.697 UTC
Prelude Turtle>
```

**Comment by snoyberg** [comment]
Can you reproduce that against `system-fileio` directly so we can eliminate an extra layer of abstraction?

**Comment by hgolden** [comment]
Please try this code:
```haskell
{-# LANGUAGE OverloadedStrings #-}
import Filesystem
import Filesystem.Path.CurrentOS
import Data.Time.Clock

main = do
    -- this succeeds
    time <- getModified "C:\\autoexec.bat"
    putStrLn $ show $ time

    -- this fails
    time <- getModified "C:\\"
    putStrLn $ show $ time
```

**Comment by snoyberg** [comment]
@DanBurton Can you test this out on Windows?

**Comment by DanBurton** [comment]
I can confirm that `getModified` does not work on directories in Windows.

```
ghci> :set -XOverloadedStrings
ghci> :m +Filesystem
ghci>
ghci> listDirectory "."
[FilePath ".\\http-client",FilePath ".\\example.hs",FilePath ".\\enclosed-exceptions"]
ghci>
ghci> getModified "example.hs" -- it works on files that exist
2015-03-19 16:07:02.265 UTC
ghci> getModified "not-there.hs" -- throws the apprioriate doesn't-exist exception
** Exception: CreateFile "not-there.hs": does not exist (The system cannot find the file specified.)
ghci>
ghci> getModified "http-client" -- you can see this dir is listed above
*** Exception: CreateFile "http-client": permission denied (Access is denied.)
ghci>
```

This is with system-fileio-0.3.16.1. I even tried using `copyPermissions "example.hs" "http-client"` to make sure they had the same permissions. The result is unchanged.

**Comment by DanBurton** [comment]
Something else I noticed is that with a trailing backslash, I get a different error message:

```
ghci> getModified "http-client\\"
*** Exception: CreateFile "http-client\\": does not exist (The system cannot fin
d the path specified.)
```

It says it doesn't exist, although `listDirectory` works just fine with the trailing backslash.

```
ghci> listDirectory "http-client\\"
[FilePath ...]

**Comment by DanBurton** [comment]
Created PR #10.

The same MSDN documentation notes that it is also essential to use `FILE_FLAG_BACKUP_SEMANTICS` in order for `CreateFile` to succeed on a directory.

On Windows, `getModified` and `getSize` now work on both files and directories. I've verified that they work for my Windows machine.

**Comment by hgolden** [comment]
Thanks for the quick response, Dan!

**Comment by snoyberg** [comment]
This is now on Hackage as 0.3.16.2. Thanks guys!
